[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "python-code-builder"
version = "0.0.1a0"
description = "A library for dynamically constructing Python code with strong, explicit scoping and symbol tracking."
readme = "README.md"
requires-python = ">=2"
license = "MIT"
authors = [
  { name="Jifeng Wu", email="jifengwu2k@gmail.com" }
]
classifiers = [
    "Programming Language :: Python :: 2",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "enum34; python_version < '3.4'",
    "typing; python_version < '3.5'"
]

[project.urls]
"Homepage" = "https://github.com/jifengwu2k/python-code-builder"
"Bug Tracker" = "https://github.com/jifengwu2k/python-code-builder/issues"